spring.application.name=gateway
eureka:
    client:
        register-with-eureka: false
server:
    port: 8222
spring.cloud.config.import-check.enabled=false
spring:
    application:
        name: gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: students
                uri: http://localhost:8090
                predicates:
                    - Path=/api/v1/students/**
                - id: schools
                uri: http://localhost:8091
                predicates:
                    - Path=/api/v1/schools/**

management:
    tracing:
        sampling:
            probability: 1.0

